---
kind: pipeline
type: docker
name: default 

steps:
        - name: greeting
          image: alpine
          commands:
                  - echo HelloWorld
                  - echo Brian this is the start
                  - echo Brian this is next addition to the text
                  - echo you missed a bt



